version: "3.3"

services:
  genshin-tg-bot:
    image: "telegraf-bot"
    container_name: "telegraf-bot"
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/app:/app/app
      - ${PWD}/config:/app/config
